#!/usr/bin/env python3
"""build_export_twins.py — GENERATE every Pine export twin from its parent strategy, and prove each
committed twin still is exactly that.

WHY A GENERATOR AND NOT A HAND-KEPT COPY
----------------------------------------
🔴 A twin is half of a parity gate. It is its parent — 1,100 to 4,300 lines — with " Export" on the
title and ONE block of `plot()` calls on the end, and five of the six were kept BY HAND: every edit
to a parent had to be pasted into its twin, and a twin that has drifted proves parity against a
file nobody trades, while the gate stays green. `build_extreme_leg.py` already generated its twin;
this does the same for all six, from one rule.

    strategies/tradingview/<name>.pine                  the strategy   — edit this
    strategies/tradingview/export_blocks/<name>.pine    its export block — edit this
    strategies/tradingview/<name>_export.pine           GENERATED — never edit it

`--check` regenerates every twin in memory and diffs it against the committed file; it is a step of
`scripts/run_all_tests.sh`. Edit a parent without regenerating and the step goes RED.

⚠ DISCOVERED BOTH WAYS, never listed. Every block file is a twin to build, and every committed
`*_export.pine` must have a block file — a twin with none is a hand-kept copy again, and that is
refused rather than skipped. Fewer than MIN_TWINS found is a FAILURE: a checker that finds nothing
and prints success is worse than none.

⚠ THE TITLE IS ANCHORED ON TEXT: the first line that starts `strategy("` gains " Export" on its
title. One rule for all six — the session-sweep twin had kept its parent's title, the only one that
did, and it follows the rule since this tool landed (one line; no column it exports moves).

⚠ PINE CAPS A SCRIPT AT 64 PLOTS, and a twin over the cap fails when it is pasted, so the build
refuses one. The count is of `plot(` calls in the whole twin — the parent's own plots count too.

⚠ A REGENERATED TWIN IS A CHANGED TWIN. An export taken off the old one is still good only if the
generated bytes did not move; `--check` says whether they did.

⚠ This does not prove a twin RIGHT, only that it is its parent plus its block — rule 14. What proves
it right is that strategy's compare_*.py going green on a real export.

Usage:
    python3 strategies/tradingview/tools/build_export_twins.py            # regenerate all six
    python3 strategies/tradingview/tools/build_export_twins.py --check    # exit 1 if one is stale

Standard library only.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

TV = Path(__file__).resolve().parents[1]
BLOCKS = TV / "export_blocks"
MIN_TWINS = 6
PLOT_CAP = 64
_TITLE = 'strategy("'


def titled(parent: str, name: str) -> str:
    """The parent with " Export" added to its strategy title."""
    lines = parent.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.startswith(_TITLE):
            end = line.index('"', len(_TITLE))
            lines[i] = line[:end] + " Export" + line[end:]
            return "".join(lines)
    raise SystemExit(f'{name}.pine has no line starting strategy(" - is it still a strategy?')


def build(name: str) -> str:
    """The twin for `name` (a parent's stem, e.g. "sos_fade_strategy"), as text."""
    parent = (TV / f"{name}.pine").read_text(encoding="utf-8")
    twin = titled(parent, name) + (BLOCKS / f"{name}.pine").read_text(encoding="utf-8")
    plots = sum(1 for line in twin.splitlines() if line.lstrip().startswith("plot("))
    if plots > PLOT_CAP:
        raise SystemExit(f"{name}_export.pine would carry {plots} plots; Pine's cap is {PLOT_CAP}")
    return twin


def write_twin(name: str) -> Path:
    """Write one twin. `build_extreme_leg.py` calls this after writing its parent."""
    out = TV / f"{name}_export.pine"
    out.write_text(build(name), encoding="utf-8")
    return out


def _names() -> list:
    return sorted(p.stem for p in BLOCKS.glob("*.pine"))


def _orphans(names) -> list:
    """Committed twins that have no block file, i.e. twins still kept by hand."""
    return sorted(
        p.name for p in TV.glob("*_export.pine") if p.name[: -len("_export.pine")] not in names
    )


def check() -> int:
    names = _names()
    bad = 0
    for orphan in _orphans(names):
        bad += 1
        print(f"🔴 {orphan} has no export_blocks/ file, so it is a hand-kept copy of its parent.")
    for name in names:
        want = build(name)
        path = TV / f"{name}_export.pine"
        have = path.read_text(encoding="utf-8") if path.exists() else ""
        if have == want:
            continue
        bad += 1
        w, h = want.splitlines(), have.splitlines()
        row = next((i for i, (a, b) in enumerate(zip(w, h)) if a != b), min(len(w), len(h)))
        print(f"🔴 {path.name} is STALE - first difference at line {row + 1}:")
        print(f"     generated: {w[row][:110] if row < len(w) else '<end of file>'}")
        print(f"     committed: {h[row][:110] if row < len(h) else '<end of file>'}")
    if len(names) < MIN_TWINS:
        print(f"🔴 SELF-TEST FAILED: {len(names)} export block(s) found, expected {MIN_TWINS}.")
        return 1
    if bad:
        print("   Edit the PARENT or its export_blocks/ file, never the twin, then run")
        print("   python3 strategies/tradingview/tools/build_export_twins.py")
        return 1
    print(f"✓ all {len(names)} export twins are their parent plus their export block")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Generate the Pine export twins from their parents.")
    ap.add_argument("--check", action="store_true", help="exit 1 if a committed twin is stale")
    args = ap.parse_args(argv)
    if args.check:
        return check()
    names = _names()
    if len(names) < MIN_TWINS:
        print(f"🔴 {len(names)} export block(s) found, expected {MIN_TWINS} - nothing written.")
        return 1
    for name in names:
        out = write_twin(name)
        print(f"wrote {out.name} ({len(out.read_text(encoding='utf-8').splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
