#!/usr/bin/env python3
"""build_export_twins.py — GENERATE every Pine export twin from its parent strategy, and prove each
committed twin still is exactly that.

WHY A GENERATOR AND NOT A HAND-KEPT COPY
----------------------------------------
🔴 A twin is half of a parity gate. It is its parent — 1,100 to 4,300 lines — with " Export" on the
title, its chart drawings removed (see the plot-cap note below) and ONE block of `plot()` calls on
the end, and five of the six were kept BY HAND: every edit
to a parent had to be pasted into its twin, and a twin that has drifted proves parity against a
file nobody trades, while the gate stays green. `build_extreme_leg.py` already generated its twin;
this does the same for all six, from one rule.

    strategies/tradingview/<name>.pine                  the strategy   — edit this
    strategies/tradingview/export_blocks/<name>.pine    its export block — edit this
    strategies/tradingview/<name>_export.pine           GENERATED — never edit it

`--check` regenerates every twin in memory and diffs it against the committed file; it is a step of
`scripts/run_all_tests.sh`. Edit a parent without regenerating and the step goes RED.

⚠ DISCOVERED BOTH WAYS, never listed. Every block file is a twin to build, and every committed
`*_export.pine` must have a block file — a twin with none is a hand-kept copy again, and that is
refused rather than skipped. Fewer than MIN_TWINS found is a FAILURE: a checker that finds nothing
and prints success is worse than none.

⚠ THE TITLE IS ANCHORED ON TEXT: the first line that starts `strategy("` gains " Export" on its
title. One rule for all six — the session-sweep twin had kept its parent's title, the only one that
did, and it follows the rule since this tool landed (one line; no column it exports moves).

⚠ PINE CAPS A SCRIPT AT 64 PLOTS, and a twin over the cap fails when it is pasted, so the build
refuses one. 🔴 **THE COUNT WAS OF `plot(` ALONE UNTIL 2026-09-16 AND THAT UNDERCOUNTS.** The cap
is on the whole PLOT FAMILY — `plotshape`, `plotchar`, `plotarrow`, `plotcandle`, `plotbar` all
consume a slot — so the realign twin built green at a counted 62 and TradingView refused it at a
real 68 the moment Aaron pasted it. A guard that misses the thing it guards against is worse than
none, because the build says the file is fine. The count is now the whole family.

🔴 **THE TWIN DOES NOT CARRY THE PARENT'S CHART DRAWINGS, AND THAT IS DELIBERATE (2026-09-16).**
A twin exists for ONE job: produce the CSV its `compare_*.py` reads. Its entry triangles, its
setup marks and its Data Window diagnostic counters are all for a human looking at the parent —
and on the twin they spend 10 to 16 of the 64 slots that the export columns need. So every
top-level call in the plot family is removed from the PARENT half; the export block's own plots
are appended afterwards and are untouched.
  · **It cannot change a single trade, and that is a language guarantee rather than a judgement.**
    `plot` and its family are output-only: they cannot assign to a variable and nothing can read
    them back, so no strategy state depends on one. Verified at the time: no parent uses `fill()`
    and none assigns a plot to a name, which are the two ways a plot could be referenced later.
  · **What the gate reads is unaffected.** Every column in `compare_realign.py`'s compared list is
    a `px_*` from the export block; no gate has ever read a parent's own plot column.
  · It buys every twin 10-16 slots of permanent headroom. Three twins were within two plots of
    the cap when this landed.

⚠ A REGENERATED TWIN IS A CHANGED TWIN. An export taken off the old one is still good only if the
generated bytes did not move; `--check` says whether they did.

⚠ This does not prove a twin RIGHT, only that it is its parent plus its block — rule 14. What proves
it right is that strategy's compare_*.py going green on a real export.

Usage:
    python3 strategies/tradingview/tools/build_export_twins.py            # regenerate all six
    python3 strategies/tradingview/tools/build_export_twins.py --check    # exit 1 if one is stale

Standard library only.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

TV = Path(__file__).resolve().parents[1]
BLOCKS = TV / "export_blocks"
MIN_TWINS = 6
PLOT_CAP = 64
_TITLE = 'strategy("'

# Every call that consumes one of the 64 slots. Anchored at column 0 because Pine only allows
# these at global scope, so an indented match would be something else entirely.
_PLOT_FAMILY = re.compile(r"^(plot|plotshape|plotchar|plotarrow|plotcandle|plotbar)\s*\(")


def _code(line: str) -> str:
    """The line with string literals and any trailing comment removed.

    ⚠ Needed for the bracket count, never for anything else: a `(` inside a plot's title or
    tooltip is not an open bracket, and a `//` inside one is not a comment. Getting this wrong
    desynchronises the depth and the strip eats the rest of the file.
    """
    out, i, quote = [], 0, ""
    while i < len(line):
        ch = line[i]
        if quote:
            if ch == "\\":
                i += 2
                continue
            if ch == quote:
                quote = ""
        elif ch in "\"'":
            quote = ch
        elif ch == "/" and line[i : i + 2] == "//":
            break
        else:
            out.append(ch)
        i += 1
    return "".join(out)


def _depth(line: str) -> int:
    body = _code(line)
    return sum(body.count(c) for c in "([{") - sum(body.count(c) for c in ")]}")


def undrawn(parent: str) -> str:
    """The parent with every top-level plot-family CALL removed — see the header.

    A call may span several lines, so it is dropped from its first line through the line where
    its brackets close, never by line count.
    """
    lines = parent.splitlines(keepends=True)
    out, i = [], 0
    while i < len(lines):
        if not _PLOT_FAMILY.match(lines[i]):
            out.append(lines[i])
            i += 1
            continue
        depth = _depth(lines[i])
        i += 1
        while depth > 0 and i < len(lines):
            depth += _depth(lines[i])
            i += 1
    return "".join(out)


def plot_count(twin: str) -> int:
    """Slots the twin consumes. Counts the whole family, and a wrapped call only once."""
    return sum(1 for line in twin.splitlines() if _PLOT_FAMILY.match(line))


def titled(parent: str, name: str) -> str:
    """The parent with " Export" added to its strategy title."""
    lines = parent.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.startswith(_TITLE):
            end = line.index('"', len(_TITLE))
            lines[i] = line[:end] + " Export" + line[end:]
            return "".join(lines)
    raise SystemExit(f'{name}.pine has no line starting strategy(" - is it still a strategy?')


def build(name: str) -> str:
    """The twin for `name` (a parent's stem, e.g. "sos_fade_strategy"), as text."""
    parent = (TV / f"{name}.pine").read_text(encoding="utf-8")
    twin = undrawn(titled(parent, name)) + (BLOCKS / f"{name}.pine").read_text(encoding="utf-8")
    plots = plot_count(twin)
    if plots > PLOT_CAP:
        raise SystemExit(f"{name}_export.pine would carry {plots} plots; Pine's cap is {PLOT_CAP}")
    return twin


def write_twin(name: str) -> Path:
    """Write one twin. `build_extreme_leg.py` calls this after writing its parent."""
    out = TV / f"{name}_export.pine"
    out.write_text(build(name), encoding="utf-8")
    return out


def _names() -> list:
    return sorted(p.stem for p in BLOCKS.glob("*.pine"))


def _orphans(names) -> list:
    """Committed twins that have no block file, i.e. twins still kept by hand."""
    return sorted(
        p.name for p in TV.glob("*_export.pine") if p.name[: -len("_export.pine")] not in names
    )


def check() -> int:
    names = _names()
    bad = 0
    for orphan in _orphans(names):
        bad += 1
        print(f"🔴 {orphan} has no export_blocks/ file, so it is a hand-kept copy of its parent.")
    for name in names:
        want = build(name)
        path = TV / f"{name}_export.pine"
        have = path.read_text(encoding="utf-8") if path.exists() else ""
        if have == want:
            continue
        bad += 1
        w, h = want.splitlines(), have.splitlines()
        row = next((i for i, (a, b) in enumerate(zip(w, h)) if a != b), min(len(w), len(h)))
        print(f"🔴 {path.name} is STALE - first difference at line {row + 1}:")
        print(f"     generated: {w[row][:110] if row < len(w) else '<end of file>'}")
        print(f"     committed: {h[row][:110] if row < len(h) else '<end of file>'}")
    if len(names) < MIN_TWINS:
        print(f"🔴 SELF-TEST FAILED: {len(names)} export block(s) found, expected {MIN_TWINS}.")
        return 1
    if bad:
        print("   Edit the PARENT or its export_blocks/ file, never the twin, then run")
        print("   python3 strategies/tradingview/tools/build_export_twins.py")
        return 1
    # ⚠ The wording earns its length. This read "are their parent plus their export block" until
    #   2026-09-16, and since the twin stopped carrying the parent's chart drawings that sentence
    #   was a FALSE claim about the file it had just verified — rule 7, from the check itself.
    print(
        f"✓ all {len(names)} export twins are their parent, minus its chart drawings, "
        f"plus their export block"
    )
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Generate the Pine export twins from their parents.")
    ap.add_argument("--check", action="store_true", help="exit 1 if a committed twin is stale")
    args = ap.parse_args(argv)
    if args.check:
        return check()
    names = _names()
    if len(names) < MIN_TWINS:
        print(f"🔴 {len(names)} export block(s) found, expected {MIN_TWINS} - nothing written.")
        return 1
    for name in names:
        out = write_twin(name)
        print(f"wrote {out.name} ({len(out.read_text(encoding='utf-8').splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
